# Generated by Django 4.2.6 on 2023-11-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='telefono',
        ),
    ]
