# Generated by Django 4.2.6 on 2023-11-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0002_remove_estacion_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='pista',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='servicio',
        ),
        migrations.CreateModel(
            name='EstacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSki.estacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSki.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='EstacionPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSki.estacion')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSki.pista')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='pistas',
            field=models.ManyToManyField(through='appSki.EstacionPista', to='appSki.pista'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='servicios',
            field=models.ManyToManyField(through='appSki.EstacionServicio', to='appSki.servicio'),
        ),
    ]
