# Generated by Django 4.2.6 on 2023-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0003_remove_estacion_pista_remove_estacion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='horario',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='precio_dia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estacion',
            name='superficie',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
    ]
