# Generated by Django 4.2.6 on 2023-11-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0004_estacion_horario_estacion_precio_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='superficie',
            field=models.FloatField(default=0.0),
        ),
    ]
