# Generated by Django 4.2.6 on 2023-11-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0006_rename_horario_estacion_horario_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='horario_ini',
        ),
    ]
