# Generated by Django 4.2.6 on 2023-11-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0007_remove_servicio_horario_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='reserva',
        ),
        migrations.AddField(
            model_name='estacionservicio',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estacionservicio',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estacionservicio',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
    ]
