# Generated by Django 4.2.6 on 2023-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0008_remove_servicio_capacidad_remove_servicio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionservicio',
            name='horario_fin',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='estacionservicio',
            name='horario_ini',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
