# Generated by Django 4.2.6 on 2023-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0010_remove_estacionservicio_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_fin',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='horario_ini',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='reserva',
            field=models.BooleanField(default=False),
        ),
    ]
