# Generated by Django 4.2.6 on 2023-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0013_fotos_localidad_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.AddField(
            model_name='estacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
