# Generated by Django 4.2.7 on 2023-12-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSki', '0015_usuario_alter_pista_color_alter_pista_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='ViajesEnGrupo',
        ),
    ]
